<?php
/**
 * ResponseCheckMultipleSchemaDataInnerConditions
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Dayonevn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant APIs
 *
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dayonevn\Model;

use \ArrayAccess;
use \Dayonevn\ObjectSerializer;

/**
 * ResponseCheckMultipleSchemaDataInnerConditions Class Doc Comment
 *
 * @category Class
 * @description Include information involve with voucher type is conditional
 * @package  Dayonevn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResponseCheckMultipleSchemaDataInnerConditions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ResponseCheckMultipleSchema_data_inner_conditions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'startDate' => 'string',
        'excludeSpecificDate' => 'string[]',
        'excludeRecurringDay' => 'string[]',
        'orderValue' => 'int',
        'redeemableSkus' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'startDate' => null,
        'excludeSpecificDate' => null,
        'excludeRecurringDay' => null,
        'orderValue' => null,
        'redeemableSkus' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'startDate' => false,
        'excludeSpecificDate' => false,
        'excludeRecurringDay' => false,
        'orderValue' => true,
        'redeemableSkus' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'startDate' => 'start_date',
        'excludeSpecificDate' => 'exclude_specific_date',
        'excludeRecurringDay' => 'exclude_recurring_day',
        'orderValue' => 'order_value',
        'redeemableSkus' => 'redeemable_skus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'startDate' => 'setStartDate',
        'excludeSpecificDate' => 'setExcludeSpecificDate',
        'excludeRecurringDay' => 'setExcludeRecurringDay',
        'orderValue' => 'setOrderValue',
        'redeemableSkus' => 'setRedeemableSkus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'startDate' => 'getStartDate',
        'excludeSpecificDate' => 'getExcludeSpecificDate',
        'excludeRecurringDay' => 'getExcludeRecurringDay',
        'orderValue' => 'getOrderValue',
        'redeemableSkus' => 'getRedeemableSkus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('startDate', $data ?? [], null);
        $this->setIfExists('excludeSpecificDate', $data ?? [], null);
        $this->setIfExists('excludeRecurringDay', $data ?? [], null);
        $this->setIfExists('orderValue', $data ?? [], null);
        $this->setIfExists('redeemableSkus', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets startDate
     *
     * @return string|null
     */
    public function getStartDate()
    {
        return $this->container['startDate'];
    }

    /**
     * Sets startDate
     *
     * @param string|null $startDate Promo start date (YYYY-MM-DD)
     *
     * @return self
     */
    public function setStartDate($startDate)
    {
        if (is_null($startDate)) {
            throw new \InvalidArgumentException('non-nullable startDate cannot be null');
        }
        $this->container['startDate'] = $startDate;

        return $this;
    }

    /**
     * Gets excludeSpecificDate
     *
     * @return string[]|null
     */
    public function getExcludeSpecificDate()
    {
        return $this->container['excludeSpecificDate'];
    }

    /**
     * Sets excludeSpecificDate
     *
     * @param string[]|null $excludeSpecificDate Promo non-effective dates (YYYY-MM-DD)
     *
     * @return self
     */
    public function setExcludeSpecificDate($excludeSpecificDate)
    {
        if (is_null($excludeSpecificDate)) {
            throw new \InvalidArgumentException('non-nullable excludeSpecificDate cannot be null');
        }
        $this->container['excludeSpecificDate'] = $excludeSpecificDate;

        return $this;
    }

    /**
     * Gets excludeRecurringDay
     *
     * @return string[]|null
     */
    public function getExcludeRecurringDay()
    {
        return $this->container['excludeRecurringDay'];
    }

    /**
     * Sets excludeRecurringDay
     *
     * @param string[]|null $excludeRecurringDay Promo non-effective day of week
     *
     * @return self
     */
    public function setExcludeRecurringDay($excludeRecurringDay)
    {
        if (is_null($excludeRecurringDay)) {
            throw new \InvalidArgumentException('non-nullable excludeRecurringDay cannot be null');
        }
        $this->container['excludeRecurringDay'] = $excludeRecurringDay;

        return $this;
    }

    /**
     * Gets orderValue
     *
     * @return int|null
     */
    public function getOrderValue()
    {
        return $this->container['orderValue'];
    }

    /**
     * Sets orderValue
     *
     * @param int|null $orderValue Order value of voucher type = conditional
     *
     * @return self
     */
    public function setOrderValue($orderValue)
    {
        if (is_null($orderValue)) {
            array_push($this->openAPINullablesSetToNull, 'orderValue');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('orderValue', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['orderValue'] = $orderValue;

        return $this;
    }

    /**
     * Gets redeemableSkus
     *
     * @return string[]|null
     */
    public function getRedeemableSkus()
    {
        return $this->container['redeemableSkus'];
    }

    /**
     * Sets redeemableSkus
     *
     * @param string[]|null $redeemableSkus List of redeemable SKUs of the voucher code. For voucher type = conditional, bill number must contain at least 1 redeemable SKU of the voucher.
     *
     * @return self
     */
    public function setRedeemableSkus($redeemableSkus)
    {
        if (is_null($redeemableSkus)) {
            throw new \InvalidArgumentException('non-nullable redeemableSkus cannot be null');
        }
        $this->container['redeemableSkus'] = $redeemableSkus;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


