<?php
/**
 * ResponseCheckMultipleSchemaV60DataInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merchant APIs
 *
 * Technical document APIs for Merchant APIs
 *
 * The version of the OpenAPI document: 6.0
 * Contact: duong.vu@gotit.vn
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ResponseCheckMultipleSchemaV60DataInner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ResponseCheckMultipleSchemaV60DataInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ResponseCheckMultipleSchemaV60_data_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'code' => 'string',
        'product' => '\OpenAPI\Client\Model\ResponseCheckMultipleSchemaV60DataInnerProduct',
        'state' => 'int',
        'usedDate' => 'string',
        'expiryDate' => 'string',
        'cancelDate' => 'string',
        'usedStore' => '\OpenAPI\Client\Model\ResponseCheckMultipleSchemaV60DataInnerUsedStore',
        'billNumber' => 'string',
        'voucherType' => 'string',
        'skusConditionVi' => 'string',
        'skusConditionEn' => 'string',
        'redeemSku' => '\OpenAPI\Client\Model\ResponseCheckMultipleSchemaV60DataInnerRedeemSku',
        'redeemableSkus' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'code' => null,
        'product' => null,
        'state' => null,
        'usedDate' => null,
        'expiryDate' => null,
        'cancelDate' => null,
        'usedStore' => null,
        'billNumber' => null,
        'voucherType' => null,
        'skusConditionVi' => null,
        'skusConditionEn' => null,
        'redeemSku' => null,
        'redeemableSkus' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'code' => false,
        'product' => false,
        'state' => true,
        'usedDate' => false,
        'expiryDate' => false,
        'cancelDate' => false,
        'usedStore' => false,
        'billNumber' => false,
        'voucherType' => false,
        'skusConditionVi' => false,
        'skusConditionEn' => false,
        'redeemSku' => false,
        'redeemableSkus' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'product' => 'product',
        'state' => 'state',
        'usedDate' => 'used_date',
        'expiryDate' => 'expiry_date',
        'cancelDate' => 'cancel_date',
        'usedStore' => 'used_store',
        'billNumber' => 'bill_number',
        'voucherType' => 'voucher_type',
        'skusConditionVi' => 'skus_condition_vi',
        'skusConditionEn' => 'skus_condition_en',
        'redeemSku' => 'redeem_sku',
        'redeemableSkus' => 'redeemable_skus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'product' => 'setProduct',
        'state' => 'setState',
        'usedDate' => 'setUsedDate',
        'expiryDate' => 'setExpiryDate',
        'cancelDate' => 'setCancelDate',
        'usedStore' => 'setUsedStore',
        'billNumber' => 'setBillNumber',
        'voucherType' => 'setVoucherType',
        'skusConditionVi' => 'setSkusConditionVi',
        'skusConditionEn' => 'setSkusConditionEn',
        'redeemSku' => 'setRedeemSku',
        'redeemableSkus' => 'setRedeemableSkus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'product' => 'getProduct',
        'state' => 'getState',
        'usedDate' => 'getUsedDate',
        'expiryDate' => 'getExpiryDate',
        'cancelDate' => 'getCancelDate',
        'usedStore' => 'getUsedStore',
        'billNumber' => 'getBillNumber',
        'voucherType' => 'getVoucherType',
        'skusConditionVi' => 'getSkusConditionVi',
        'skusConditionEn' => 'getSkusConditionEn',
        'redeemSku' => 'getRedeemSku',
        'redeemableSkus' => 'getRedeemableSkus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('usedDate', $data ?? [], null);
        $this->setIfExists('expiryDate', $data ?? [], null);
        $this->setIfExists('cancelDate', $data ?? [], null);
        $this->setIfExists('usedStore', $data ?? [], null);
        $this->setIfExists('billNumber', $data ?? [], null);
        $this->setIfExists('voucherType', $data ?? [], null);
        $this->setIfExists('skusConditionVi', $data ?? [], null);
        $this->setIfExists('skusConditionEn', $data ?? [], null);
        $this->setIfExists('redeemSku', $data ?? [], null);
        $this->setIfExists('redeemableSkus', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code Voucher code
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets product
     *
     * @return \OpenAPI\Client\Model\ResponseCheckMultipleSchemaV60DataInnerProduct|null
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \OpenAPI\Client\Model\ResponseCheckMultipleSchemaV60DataInnerProduct|null $product product
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets state
     *
     * @return int|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param int|null $state State of voucher
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            array_push($this->openAPINullablesSetToNull, 'state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets usedDate
     *
     * @return string|null
     */
    public function getUsedDate()
    {
        return $this->container['usedDate'];
    }

    /**
     * Sets usedDate
     *
     * @param string|null $usedDate Date voucher marked as used in case the voucher has been redeemed. Format (YYYY-MM-DD HH:MM:SS)
     *
     * @return self
     */
    public function setUsedDate($usedDate)
    {
        if (is_null($usedDate)) {
            throw new \InvalidArgumentException('non-nullable usedDate cannot be null');
        }
        $this->container['usedDate'] = $usedDate;

        return $this;
    }

    /**
     * Gets expiryDate
     *
     * @return string|null
     */
    public function getExpiryDate()
    {
        return $this->container['expiryDate'];
    }

    /**
     * Sets expiryDate
     *
     * @param string|null $expiryDate Expiry date of voucher (YYYY-MM-DD)
     *
     * @return self
     */
    public function setExpiryDate($expiryDate)
    {
        if (is_null($expiryDate)) {
            throw new \InvalidArgumentException('non-nullable expiryDate cannot be null');
        }
        $this->container['expiryDate'] = $expiryDate;

        return $this;
    }

    /**
     * Gets cancelDate
     *
     * @return string|null
     */
    public function getCancelDate()
    {
        return $this->container['cancelDate'];
    }

    /**
     * Sets cancelDate
     *
     * @param string|null $cancelDate Date cancel voucher (YYYY-MM-DD)
     *
     * @return self
     */
    public function setCancelDate($cancelDate)
    {
        if (is_null($cancelDate)) {
            throw new \InvalidArgumentException('non-nullable cancelDate cannot be null');
        }
        $this->container['cancelDate'] = $cancelDate;

        return $this;
    }

    /**
     * Gets usedStore
     *
     * @return \OpenAPI\Client\Model\ResponseCheckMultipleSchemaV60DataInnerUsedStore|null
     */
    public function getUsedStore()
    {
        return $this->container['usedStore'];
    }

    /**
     * Sets usedStore
     *
     * @param \OpenAPI\Client\Model\ResponseCheckMultipleSchemaV60DataInnerUsedStore|null $usedStore usedStore
     *
     * @return self
     */
    public function setUsedStore($usedStore)
    {
        if (is_null($usedStore)) {
            throw new \InvalidArgumentException('non-nullable usedStore cannot be null');
        }
        $this->container['usedStore'] = $usedStore;

        return $this;
    }

    /**
     * Gets billNumber
     *
     * @return string|null
     */
    public function getBillNumber()
    {
        return $this->container['billNumber'];
    }

    /**
     * Sets billNumber
     *
     * @param string|null $billNumber Bill number
     *
     * @return self
     */
    public function setBillNumber($billNumber)
    {
        if (is_null($billNumber)) {
            throw new \InvalidArgumentException('non-nullable billNumber cannot be null');
        }
        $this->container['billNumber'] = $billNumber;

        return $this;
    }

    /**
     * Gets voucherType
     *
     * @return string|null
     */
    public function getVoucherType()
    {
        return $this->container['voucherType'];
    }

    /**
     * Sets voucherType
     *
     * @param string|null $voucherType Voucher type, standard or redeemable_sku
     *
     * @return self
     */
    public function setVoucherType($voucherType)
    {
        if (is_null($voucherType)) {
            throw new \InvalidArgumentException('non-nullable voucherType cannot be null');
        }
        $this->container['voucherType'] = $voucherType;

        return $this;
    }

    /**
     * Gets skusConditionVi
     *
     * @return string|null
     */
    public function getSkusConditionVi()
    {
        return $this->container['skusConditionVi'];
    }

    /**
     * Sets skusConditionVi
     *
     * @param string|null $skusConditionVi Voucher SKU terms and conditions description in Vietnamese
     *
     * @return self
     */
    public function setSkusConditionVi($skusConditionVi)
    {
        if (is_null($skusConditionVi)) {
            throw new \InvalidArgumentException('non-nullable skusConditionVi cannot be null');
        }
        $this->container['skusConditionVi'] = $skusConditionVi;

        return $this;
    }

    /**
     * Gets skusConditionEn
     *
     * @return string|null
     */
    public function getSkusConditionEn()
    {
        return $this->container['skusConditionEn'];
    }

    /**
     * Sets skusConditionEn
     *
     * @param string|null $skusConditionEn Voucher SKU terms and conditions description in English
     *
     * @return self
     */
    public function setSkusConditionEn($skusConditionEn)
    {
        if (is_null($skusConditionEn)) {
            throw new \InvalidArgumentException('non-nullable skusConditionEn cannot be null');
        }
        $this->container['skusConditionEn'] = $skusConditionEn;

        return $this;
    }

    /**
     * Gets redeemSku
     *
     * @return \OpenAPI\Client\Model\ResponseCheckMultipleSchemaV60DataInnerRedeemSku|null
     */
    public function getRedeemSku()
    {
        return $this->container['redeemSku'];
    }

    /**
     * Sets redeemSku
     *
     * @param \OpenAPI\Client\Model\ResponseCheckMultipleSchemaV60DataInnerRedeemSku|null $redeemSku redeemSku
     *
     * @return self
     */
    public function setRedeemSku($redeemSku)
    {
        if (is_null($redeemSku)) {
            throw new \InvalidArgumentException('non-nullable redeemSku cannot be null');
        }
        $this->container['redeemSku'] = $redeemSku;

        return $this;
    }

    /**
     * Gets redeemableSkus
     *
     * @return string[]|null
     */
    public function getRedeemableSkus()
    {
        return $this->container['redeemableSkus'];
    }

    /**
     * Sets redeemableSkus
     *
     * @param string[]|null $redeemableSkus List of redeemable SKUs of the voucher code. For voucher type = redeemable_sku, bill number must contain at least 1 redeemable SKU of the voucher.
     *
     * @return self
     */
    public function setRedeemableSkus($redeemableSkus)
    {
        if (is_null($redeemableSkus)) {
            throw new \InvalidArgumentException('non-nullable redeemableSkus cannot be null');
        }
        $this->container['redeemableSkus'] = $redeemableSkus;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


